version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    networks:
      - emp_network

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: php-fpm
    # 移除 volumes 掛載，依賴 Dockerfile 中的 COPY src
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
    networks:
      - emp_network
    environment:
      - APP_KEY=${APP_KEY}
      - APP_ENV=${APP_ENV}
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - ELASTICSEARCH_HOST=elasticsearch
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - BQ_DATASET_ID=${BQ_DATASET_ID}
      - BQ_SERVICE_ACCOUNT_FILE=${BQ_SERVICE_ACCOUNT_FILE}
      - SENTRY_DSN=${SENTRY_DSN}
      - AI_SERVICE_URL=${AI_SERVICE_URL}

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - emp_network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - emp_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - emp_network

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - emp_network

volumes:
  db_data:
  es_data:

networks:
  emp_network:
    driver: bridge
